
2021-08-11 15:24:36,230 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:474]
2021-08-11 15:24:39,852 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:474]
2021-08-11 15:25:35,747 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 15:36:35,961 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 15:36:50,149 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 15:58:43,560 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 15:58:46,555 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 425, in shows
    for show in shows:
TypeError: 'function' object is not iterable
2021-08-11 16:02:46,554 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:02:53,212 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:03:18,561 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 393, in _resolve_name
    rval = d[token]
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
KeyError: 'Shows'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3423, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1890, in _post_configure_properties
    prop.init()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\interfaces.py", line 222, in init
    self.do_init()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2140, in do_init
    self._process_dependent_arguments()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2235, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2102, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:03:22,084 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:03:51,387 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:03:58,020 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:04:03,315 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 393, in _resolve_name
    rval = d[token]
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
KeyError: 'Shows'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3423, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1890, in _post_configure_properties
    prop.init()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\interfaces.py", line 222, in init
    self.do_init()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2140, in do_init
    self._process_dependent_arguments()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2235, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2102, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:04:53,624 INFO: errors [in c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:04:56,380 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 393, in _resolve_name
    rval = d[token]
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_collections.py", line 746, in __missing__
    self[key] = val = self.creator(key)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 372, in _access_cls
    return self.fallback[key]
KeyError: 'Shows'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3423, in _do_configure_registries
    mapper._post_configure_properties()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1890, in _post_configure_properties
    prop.init()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\interfaces.py", line 222, in init
    self.do_init()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2140, in do_init
    self._process_dependent_arguments()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2235, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\relationships.py", line 2102, in entity
    argument = self._clsregistry_resolve_name(self.argument)()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 397, in _resolve_name
    self._raise_for_name(name, err)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 375, in _raise_for_name
    util.raise_(
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:05:33,440 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:05:42,584 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:05:50,229 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:05:51,714 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:08:00,710 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:08:11,365 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:08:14,896 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:08:20,174 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:09:14,323 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:13:22,357 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:13:23,744 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
2021-08-11 16:13:37,499 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:13:39,920 INFO: errors [in C:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py:473]
2021-08-11 16:32:06,123 ERROR: Exception on /shows [GET] [in C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\Cedge\Documents\VS-code-projects\fyyur-project\app.py", line 424, in shows
    shows = Show.query.join(Venue, Show.venue_id == Venue.id).join(Artist, Artist.id == Show.artist_id).all()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 1873, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3384, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Cedge\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\mapper.py", line 3419, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class Venue->venue'. Original exception was: When initializing mapper mapped class Venue->venue, expression 'Shows' failed to locate a name ('Shows'). If this is a class name, consider adding this relationship() to the <class 'models.Venue'> class after both dependent classes have been defined.
